### ISSUE TITLE
 Blocks of type "block_device_mappings" are not expected here

### ISSUE THREAD

**Issue by Pzharyuk** [spotinst/terraform-spotinst-ocean-aws-k8s#17]
**What happened**:
```
╷
│ Error: Unsupported block type
│ 
│   on .terraform/modules/ocean-aws-k8s/ocean.tf line 168, in resource "spotinst_ocean_aws" "ocean":
│  168:   dynamic "block_device_mappings" {
│ 
│ Blocks of type "block_device_mappings" are not expected here.
```

I do see this change made in history:

![image](https://github.com/spotinst/terraform-spotinst-ocean-aws-k8s/assets/22070203/d98a57d6-72e1-4e23-8e6e-4428d9bfc6f4)

**What you expected to happen**:

Plan needs to execute without errors

**How to reproduce it (as minimally and precisely as possible):**
Make sure to run "terraform init" in a clean environment with the latest version of spotinst-ocean-aws-k8s  module

- Terraform version: 1.5.6
- Module version: 0.3.0
- OS: Mac

**Comment by chandra1-n** [comment]
@Pzharyuk Thanks for identifying the issue, we have made the fix on `block_device_mappings` recently and released, please try this with latest version of the module. Closing this issue.
