### ISSUE TITLE
resource_tag_specification not available please add 

### ISSUE THREAD

**Issue by alexgoddity** [spotinst/terraform-spotinst-ocean-aws-k8s#30]
need to be added in module
https://registry.terraform.io/providers/spotinst/spotinst/latest/docs/resources/ocean_aws#:~:text=resource_tag_specification%20%7B%0A%20%20%20%20should_tag_volumes%20%3D%20true%0A%20%20%7D

**What would you like to be added?**
  resource_tag_specification {
    should_tag_volumes = true
  }
**Why is this needed?**
to enable tags for volumes

**Comment by victorcechinel** [comment]
Same here

**Comment by anuragsharma-123** [comment]
@alexgoddity @victorcechinel - The support is added in v1.1.0. Please check.
