### ISSUE TITLE
worker_instance_profile_arn not null

### ISSUE THREAD

**Issue by victorcechinel** [spotinst/terraform-spotinst-ocean-aws-k8s#31]
**What happened**:

The `worker_instance_profile_arn` variable is [not accepting null values](https://github.com/spotinst/terraform-spotinst-ocean-aws-k8s/blob/main/variables.tf#L87-L90), however, when a cluster is created using the Spot UI, it is possible not to place an Instance Profile.

![image](https://github.com/spotinst/terraform-spotinst-ocean-aws-k8s/assets/132499621/9470aa82-2428-4d16-b6b6-db1fc062f41b)

**What you expected to happen**:
The `worker_instance_profile_arn` variable accepted null value.

**How to reproduce it (as minimally and precisely as possible):**

1. Use the module omitting the variable `worker_instance_profile_arn`;

**Environment:**

- _Terraform version_: **v1.5.2**
- _Module version_: **0.4.1**
- _OS_: **macOS 14.2.1 (23C71)**
- _Kernel_: **Darwin Kernel Version 23.2.0**
- _Others_:
  - _Terragrunt version_: **v0.54.5**

**Comment by felipeIntelipost** [comment]
I'm having the same problem here

**Comment by sobhanagit** [comment]
We have released the fix for this issue. Currently The worker_instance_profile_arn variable accepts null value.
